dataset:
  marketing:
    dataset_id: "mktg_dataset"
    dataset_name: "mktg_dataset"
    dataset_desc: "testing"
    labels:
      owner: "marketing"
      sensitivity: "high"

  finance:
    dataset_id: "fin_dataset"