dataset:
  marketing:
    dataset_id: "mktg_dataset"
    dataset_name: "mktg_dataset"
    dataset_desc: "testing"
    labels:
      owner: "marketing"
      sensitivity: "high"
      app-own: "unknown"
      res-name: "mktg"

  finance:
    dataset_id: "fin_dataset"
    labels:
      app-own: "unknown"
      res-name: "mktg"