dataset:
  marketing:
    id: "mktg_dataset"
    name: "mktg_dataset"
    description: "testing"
    labels:
      owner: "marketing"
      sensitivity: "high"

  finance:
    dataset_id: "fin_dataset"