environments:
  dev:
    project_id: gleaming-nomad-474505-r3
    location: us-east4

    reservations:
      analytics-res:
        slot_capacity: 50
        edition: STANDARD
        ignore_idle_slots: false

        assignments:
          - assignee_type: PROJECT
            assignee_id: my-dev-project
            job_type: QUERY

          - assignee_type: FOLDER
            assignee_id: "123456789012"
            job_type: PIPELINE

      etl-res:
        slot_capacity: 100
        edition: ENTERPRISE
        ignore_idle_slots: true

        assignments:
          - assignee_type: PROJECT
            assignee_id: etl-dev-project
            job_type: QUERY

  prod:
    project_id: my-prod-project
    location: US

    reservations:
      analytics-res:
        slot_capacity: 100
        edition: ENTERPRISE
        ignore_idle_slots: false

        assignments:
          - assignee_type: PROJECT
            assignee_id: my-prod-project
            job_type: QUERY
