name: terraform initializing

on:
  push:
    branches:
      - feature-*

jobs:
  terraform-chg:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v5
      - name: setup
        uses: hashicorp/setup-terraform@v3
      - name: Authentication
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          #with:
           # terraform_version: "1.1.7"
      - name: Run terraform init
        run: terraform init
      - name: Run terraform validate & plan
        run: terraform validate
          #echo ""
          #echo "terraform plan"
      - name: terraform plan
        run: terraform plan


      

